theme: jekyll-theme-merlot
title: Predicting the 2018 Midterms
description: AC209A Final Project
baseurl:
markdown: kramdown
kramdown:
    math_engine: mathjax
    input: GFM
    syntax_highlighter: rouge
